name: Keep Server Awake
on:
  schedule:
    - cron: "*/14 * * * *" # Chạy mỗi 14 phút
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render Endpoint
        run: curl https://timetable-backend-1jqm.onrender.com/api/health-check
